
<div id="product-commect-container" data-role="product-comment"></div>

<?= $block->getChildHtml() ?>


<script type="text/x-magento-init">
    {
        "*": {
            "Certification_ProductComment/js/process-comments": {
                "productCommentUrl": "<?= $block->escapeJs($block->escapeUrl($block->getproductCommentUrl())) ?>",
                "commectTabSelector": "#tab-label-comments"
            }
        }
    }
</script>