<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var \Magento\Review\Block\Form $block */
?>
<div class="block comment-add">
    <div class="block-title"><strong><?= $block->escapeHtml(__('Write Your Own Comment')) ?></strong></div>
    <div class="block-content">

        <form action="<?= $block->escapeUrl($block->getAction()) ?>" class="comment-form" method="post" id="comment-form"
              data-role="product-comment-form" data-bind="scope: 'comment-form'">
            <?= $block->getBlockHtml('formkey') ?>
            <?= $block->getChildHtml('form_fields_before') ?>
            <fieldset class="fieldset comment-fieldset"
                      data-hasrequired="<?= $block->escapeHtmlAttr(__('* Required Fields')) ?>">
                <legend class="legend comment-legend">
                    <span><?= $block->escapeHtml(__("You're commenting:")) ?></span><strong><?= $block->escapeHtml($block->getProductInfo()->getName()) ?></strong>
                </legend>
                <br/>

                <div class="field comment-field-nickname required">
                    <label for="email_field"
                           class="label"><span><?= $block->escapeHtml(__('Email')) ?></span></label>
                    <div class="control">
                        <input type="text" name="email" id="email_field" class="input-email"
                               data-validate="{required:true}" />
                    </div>
                </div>
                <div class="field comment-field-text required">
                    <label for="comment_field" class="label"><span><?= $block->escapeHtml(__('Comment')) ?></span></label>
                    <div class="control">
                        <textarea name="comment" id="comment_field" cols="5" rows="3" data-validate="{required:true}"></textarea>
                    </div>
                </div>
            </fieldset>
            <div class="actions-toolbar comment-form-actions">
                <div class="primary actions-primary">
                    <button type="submit" class="action submit primary">
                        <span><?= $block->escapeHtml(__('Submit Comment')) ?></span></button>
                </div>
            </div>
        </form>

    </div>
</div>
