<?php /* Learning\FrontendCrud\Block\Index\Form $block */?>


<?php if($block->getRequest()->getParam('id')) : ?>
    <!-- Update form -->
<form class="form CrudForm"
      action="<?= $block->escapeUrl($block->getFomActionUrl()) ?>"
      id="crud-form"
      method="post"
      data-hasrequired="<?= $block->escapeHtmlAttr(__('* Required Fields')) ?>"
      data-mage-init='{"validation":{}}'>
    <input type="hidden" name='id' value="<?php echo $block->getItem()->getData('id')?>" />
    <fieldset class="fieldset">
        <legend class="legend"><span><?= $block->escapeHtml(__('Fill up the form')) ?></span></legend><br />

        <div class="field name required">
            <label class="label" for="name"><span><?= $block->escapeHtml(__('Name')) ?></span></label>
            <div class="control">
                <input name="name" id="name" title="<?= $block->escapeHtmlAttr(__('Name')) ?>" value="<?= $block->getItem()->getData('name') ?>" class="input-text" type="text" data-validate="{required:true}"/>
            </div>
        </div>

        <div class="field email required">
            <label class="label" for="email"><span><?= $block->escapeHtml(__('Email')) ?></span></label>
            <div class="control">
                <input name="email" id="email" title="<?= $block->escapeHtmlAttr(__('Email')) ?>" value="<?= $block->getItem()->getData('email')  ?>" class="input-text" type="email" data-validate="{required:true, 'validate-email':true}"/>
            </div>
        </div>
        <div class="field telephone">
            <label class="label" for="telephone"><span><?= $block->escapeHtml(__('Phone Number')) ?></span></label>
            <div class="control">
                <input name="telephone" id="telephone" title="<?= $block->escapeHtmlAttr(__('Phone Number')) ?>" value="<?= $block->getItem()->getData('telephone') ?>" class="input-text" type="text" />
            </div>
        </div>
        <div class="field comment required">
            <label class="label" for="comment"><span><?= $block->escapeHtml(__('What’s on your mind?')) ?></span></label>
            <div class="control">
                <textarea name="comment" id="comment" title="<?= $block->escapeHtmlAttr(__('What’s on your mind?')) ?>" class="input-text" cols="5" rows="3" data-validate="{required:true}"><?= $block->getItem()->getData('comment') ?></textarea>
            </div>
        </div>
    </fieldset>
    <div class="actions-toolbar">
        <div class="primary">
            <input type="hidden" name="hideit" id="hideit" value="" />
            <button type="submit" title="<?= $block->escapeHtmlAttr(__('Submit')) ?>" class="action submit primary">
                <span><?= $block->escapeHtml(__('Submit')) ?></span>
            </button>
        </div>
    </div>
</form>
<?php else : ?>
    <!-- add form -->
    <form class="form CrudForm"
          action="<?= $block->escapeUrl($block->getFomActionUrl()) ?>"
          id="crud-form"
          method="post"
          data-hasrequired="<?= $block->escapeHtmlAttr(__('* Required Fields')) ?>"
          data-mage-init='{"validation":{}}'>
        <fieldset class="fieldset">
            <legend class="legend"><span><?= $block->escapeHtml(__('Fill up the form')) ?></span></legend><br />

            <div class="field name required">
                <label class="label" for="name"><span><?= $block->escapeHtml(__('Name')) ?></span></label>
                <div class="control">
                    <input name="name" id="name" title="<?= $block->escapeHtmlAttr(__('Name')) ?>" value="<?= $block->escapeHtmlAttr($this->helper(\Learning\FrontendCrud\Helper\Data::class)->getPostValue('name') ?: $this->helper(\Learning\FrontendCrud\Helper\Data::class)->getUserName()) ?>" class="input-text" type="text" data-validate="{required:true}"/>
                </div>
            </div>

            <div class="field email required">
                <label class="label" for="email"><span><?= $block->escapeHtml(__('Email')) ?></span></label>
                <div class="control">
                    <input name="email" id="email" title="<?= $block->escapeHtmlAttr(__('Email')) ?>" value="<?= $block->escapeHtmlAttr($this->helper(\Learning\FrontendCrud\Helper\Data::class)->getPostValue('email') ?: $this->helper(\Learning\FrontendCrud\Helper\Data::class)->getUserEmail()) ?>" class="input-text" type="email" data-validate="{required:true, 'validate-email':true}"/>
                </div>
            </div>
            <div class="field telephone">
                <label class="label" for="telephone"><span><?= $block->escapeHtml(__('Phone Number')) ?></span></label>
                <div class="control">
                    <input name="telephone" id="telephone" title="<?= $block->escapeHtmlAttr(__('Phone Number')) ?>" value="<?= $block->escapeHtmlAttr($this->helper(\Learning\FrontendCrud\Helper\Data::class)->getPostValue('telephone')) ?>" class="input-text" type="text" />
                </div>
            </div>
            <div class="field comment required">
                <label class="label" for="comment"><span><?= $block->escapeHtml(__('What’s on your mind?')) ?></span></label>
                <div class="control">
                    <textarea name="comment" id="comment" title="<?= $block->escapeHtmlAttr(__('What’s on your mind?')) ?>" class="input-text" cols="5" rows="3" data-validate="{required:true}"><?= $block->escapeHtml($this->helper(\Learning\FrontendCrud\Helper\Data::class)->getPostValue('comment')) ?></textarea>
                </div>
            </div>
        </fieldset>
        <div class="actions-toolbar">
            <div class="primary">
                <input type="hidden" name="hideit" id="hideit" value="" />
                <button type="submit" title="<?= $block->escapeHtmlAttr(__('Submit')) ?>" class="action submit primary">
                    <span><?= $block->escapeHtml(__('Submit')) ?></span>
                </button>
            </div>
        </div>
    </form>
<?php endif;?>
